### PR TITLE
ShareX Catppuccin Previews (and new theme)

### PR DESCRIPTION
**Pull request by kingofcube**
new theme is latte :3 (sorry that i didnt do the others im too lazy)

### CODE REVIEW

**Comment by kingofcube** [comment]
emmmm

**Comment by kingofcube** [comment]
:3

**Comment by Dukeatron** [comment]
Approved. Merging

**Review by Dukeatron — APPROVED** [review]
Looks good

**Comment by kingofcube** [comment]
im still waiting

**Comment by kingofcube** [comment]
://///

**Comment by kingofcube** [comment]
????????????????????????? when merge

**Comment by kingofcube** [comment]
its already been a week...

**Comment by Dukeatron** [comment]
I think you have access too
Or check with Winston, cause I cant seem to merge it in

**Comment by sgoudham** [comment]
Hey, I'm in the process of rewriting the theme on a new branch so I temporarily took permissions away.
You can view it in the `rewrite` branch, hope that's okay with you both.

**Comment by kingofcube** [comment]
> Hey, I'm in the process of rewriting the theme on a new branch so I temporarily took permissions away. You can view it in the `rewrite` branch, hope that's okay with you both.

._. well ok ig

**Comment by sgoudham** [comment]
Apologies for not communicating my rewrite which was in progress, closing this as #6 has been merged.

**Pull request closed without merging**
